import type { Course } from "./types"

export const courseData: Course[] = [
  // Foundation Level - Data Science
  {
    id: "mds1",
    name: "Mathematics 1",
    degree: "data-science",
    level: "foundation",
    formula: "T = 0.1 * GAA + max(0.6 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.2 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "eng1",
    name: "English 1",
    degree: "data-science",
    level: "foundation",
    formula: "T = 0.1 * GAA + max(0.6 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.2 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "ct",
    name: "Computational Thinking",
    degree: "data-science",
    level: "foundation",
    formula: "T = 0.1 * GAA + max(0.6 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.2 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "stats1",
    name: "Statistics 1",
    degree: "data-science",
    level: "foundation",
    formula: "T = 0.1 * GAA + max(0.6 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.2 * Qz1 + 0.3 * Qz2) + Bonus marks",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
      { id: "Extra", label: "Extra Activity", description: "Extra Activity Marks", max: 5 },
    ],
  },
  {
    id: "stats2",
    name: "Statistics 2",
    degree: "data-science",
    level: "foundation",
    formula: "T = 0.1 * GAA + max(0.6 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.2 * Qz1 + 0.3 * Qz2) + Bonus marks",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
      { id: "Extra", label: "Extra Activity", description: "Extra Activity Marks", max: 5 },
    ],
  },
  {
    id: "mds2",
    name: "Mathematics 2",
    degree: "data-science",
    level: "foundation",
    formula: "T = min( (0.1 * GAA + max(0.6 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.2 * Qz1 + 0.3 * Qz2)) * (1 + 0.01 * B), 100)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
      { id: "Extra", label: "Extra Activity", description: "Extra Activity Marks (out of 6)", max: 6 } 
    ],
}
  },
  {
    id: "eng2",
    name: "English 2",
    degree: "data-science",
    level: "foundation",
    formula: "T = 0.1 * GAA + max(0.6 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.2 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "python",
    name: "Python Programming",
    degree: "data-science",
    level: "foundation",
    formula: "T = 0.1 * GAA1 + 0.1 * GAA2 + 0.1 * Qz1 + 0.4 * F + 0.25 * max(PE1, PE2) + 0.15 * min(PE1, PE2)",
    formFields: [
      { id: "GAA1", label: "GAA 1", description: "Graded Assignment Average 1", max: 100 },
      { id: "GAA2", label: "GAA 2", description: "Graded Assignment Average 2", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
      { id: "PE1", label: "OPPE 1", description: "Online Programming Practice Exam 1", max: 100 },
      { id: "PE2", label: "OPPE 2", description: "Online Programming Practice Exam 2", max: 100 },
    ],
  },

  // Diploma Level - Data Science (Adding a few examples)
  {
    id: "mlf",
    name: "Machine Learning Foundations",
    degree: "data-science",
    level: "diploma",
    formula: "T = 0.1 * GAA + max(0.6 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.2 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "mlt",
    name: "Machine Learning Techniques",
    degree: "data-science",
    level: "diploma",
    formula: "T = 0.1 * GAA + 0.4 * F + max(0.25 * Qz1 + 0.25 * Qz2, 0.4 * max(Qz1, Qz2))",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "mlp",
    name: "Machine Learning Practice",
    degree: "data-science",
    level: "diploma",
    formula: "T = 0.1 * GAA + 0.30 * F + 0.20 * OPE1 + 0.20 * OPE2 + 0.20 * KA",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "KA", label: "KA", description: "Kaggle Assignment score", max: 100 },
      { id: "OPE1", label: "OPE 1", description: "Online Programming Exam 1", max: 100 },
      { id: "OPE2", label: "OPE 2", description: "Online Programming Exam 2", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "bdm",
    name: "Business Data Management",
    degree: "data-science",
    level: "diploma",
    formula: "T = 0.3 * GA + 0.2 * Q2 + 0.2 * ROE + 0.3 * F",
    formFields: [
      { id: "GA", label: "GA", description: "Graded Assignment Average", max: 100 },
      { id: "Q2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "ROE", label: "ROE", description: "Review of Evaluation", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "ban",
    name: "Business Analytics",
    degree: "data-science",
    level: "diploma",
    formula: "Qz = 0.7 * max(Qz1, Qz2) + 0.3 * min(Qz1, Qz2)",
    formFields: [
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
    ],
  },
  {
    id: "tds",
    name: "Tools in Data Science",
    degree: "data-science",
    level: "diploma",
    formula: "T = 0.20 * GAA + 0.2 * ROE1 + 0.2 * P1 + 0.2 * P2 + 0.20 * F",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "ROE1", label: "ROE 1", description: "Review of Evaluation 1", max: 100 },
      { id: "P1", label: "Project 1", description: "First Project Score", max: 100 },
      { id: "P2", label: "Project 2", description: "Second Project Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "dl-genAI",
    name: "Intro to DL and GenAI",
    degree: "data-science",
    level: "diploma",
    formula: "T = 0.20 * GAA + 0.15 * Qz1 + 0.15 * Qz2 + 0.2 * F + 0.15 * NPPE1 + 0.15 * NPPE2",
    formFields: [
    { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
    { id: "Qz1", label: "Quiz 1", description: "Quiz1", max: 100 },
    { id: "Qz2", label: "Quiz 2", description: "Quiz2", max: 100 },
    { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    { id: "NPPE1", label: "NPPE 1", description: "Non - Proctored Programming Exam 1", max: 100 },
    { id: "NPPE2", label: "NPPE 2", description: "Non - Proctored Programming Exam 2", max: 100 },
    ],
  },
  {
    id: "pds",
    name: "PDSA",
    degree: "data-science",
    level: "diploma",
    formula: "T = 0.1 * GAA + 0.4 * F + 0.2 * OP + max(0.2 * max(Qz1, Qz2), (0.15 * Qz1 + 0.15 * Qz2))",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "OP", label: "OP", description: "Online Programming Exam", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "dbms",
    name: "DBMS",
    degree: "data-science",
    level: "diploma",
    formula:
      "T = 0.04 * GAA1 + 0.03 * GAA2 + 0.03 * GAA3 + 0.2 * OP + max(0.45 * F + 0.15 * max(Qz1, Qz2), 0.4 * F + (0.10 * Qz1 + 0.20 * Qz2))",
    formFields: [
      { id: "GAA1", label: "GAA 1", description: "Graded Assignment 1", max: 100 },
      { id: "GAA2", label: "GAA 2", description: "Graded Assignment 2", max: 100 },
      { id: "GAA3", label: "GAA 3", description: "Graded Assignment 3", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "OP", label: "OP", description: "Online Programming Exam", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "ad1",
    name: "AppDev-1",
    degree: "data-science",
    level: "diploma",
    formula: "T = 0.15 * GLA + 0.05 * GA + max(0.35 * F + 0.2 * Qz1 + 0.25 * Qz2, 0.4 * F + 0.3 * max(Qz1, Qz2))",
    formFields: [
      { id: "GLA", label: "GLA", description: "Graded Lab Average", max: 100 },
      { id: "GA", label: "GA", description: "Graded Assignment", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "java",
    name: "Programming Concepts using Java",
    degree: "data-science",
    level: "diploma",
    formula:
      "T = 0.1 * GAA + 0.3 * F + 0.2 * max(PE1, PE2) + 0.10 * min(PE1, PE2) + max(0.25 * max(Qz1, Qz2), 0.15 * Qz1 + 0.25 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "PE1", label: "PE 1", description: "Programming Exam 1", max: 100 },
      { id: "PE2", label: "PE 2", description: "Programming Exam 2", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "sys",
    name: "System Commands",
    degree: "data-science",
    level: "diploma",
    formula: "T = 0.10 * GAA + 0.2 * Qz1 + 0.3 * OPE + 0.3 * F + 0.1 * BPTA",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "Quiz Score", max: 100 },
      { id: "OPE", label: "OPE", description: "Online Programming Exam", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
      { id: "BPTA", label: "BPTA", description: "Best Practice Test Average", max: 100 },
    ],
  },
  {
    id: "ad2",
    name: "AppDev-2",
    degree: "data-science",
    level: "diploma",
    formula: "T = 0.05 * GAA1 + 0.05 * GAA2 + max(0.35 * F + 0.25 * Qz1 + 0.3 * Qz2, 0.5 * F + 0.3 * max(Qz1, Qz2))",
    formFields: [
      { id: "GAA1", label: "GAA 1", description: "Graded Assignment 1", max: 100 },
      { id: "GAA2", label: "GAA 2", description: "Graded Assignment 2", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },

  // Degree Level - Data Science (Adding a few examples)
  {
    id: "st",
    name: "Software Testing",
    degree: "data-science",
    level: "degree",
    formula: "T = 0.1 * GAA + 0.4 * F + 0.25 * Qz1 + 0.25 * Qz2",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "se",
    name: "Software Engineering",
    degree: "data-science",
    level: "degree",
    formula: "T = 0.05 * GAA + 0.2 * Qz2 + 0.4 * F + 0.1 * GP1 + 0.1 * GP2 + 0.1 * PP + 0.05 * CP",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
      { id: "GP1", label: "Group Project 1", description: "First Group Project Score", max: 100 },
      { id: "GP2", label: "Group Project 2", description: "Second Group Project Score", max: 100 },
      { id: "PP", label: "Peer Performance", description: "Peer Performance Score", max: 100 },
      { id: "CP", label: "Class Participation", description: "Class Participation Score", max: 100 },
    ],
  },
  {
    id: "dl",
    name: "Deep Learning",
    degree: "data-science",
    level: "degree",
    formula: "T = 0.1 * GAA + max((0.4 * F + 0.25 * Qz1 + 0.25 * Qz2), (0.5 * F + 0.3 * max(Qz1, Qz2))) + Bonus",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "ai-search",
    name: "AI: Search Methods for Problem Solving",
    degree: "data-science",
    level: "degree",
    formula: "T = 0.1 * GAA + max(0.45 * F + 0.35 * max(Qz1, Qz2), 0.4 * F + 0.25 * Qz1 + 0.25 * Qz2) + Bonus",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "llm",
    name: "Large Language Models",
    degree: "data-science",
    level: "degree",
    formula: "T = 0.1 * GAA + 0.4 * F + 0.25 * Qz1 + 0.25 * Qz2 + Bonus",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },

  {
    id: "spg",
    name: "Strategies for Professional Growth",
    degree: "data-science",
    level: "degree",
    formula: "T = 0.15 * GAA + 0.25 * GP + 0.25 * Qz2 + 0.35 * F",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "GP", label: "Group Project", description: "Group Project Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "ibd",
    name: "Introduction to Big Data",
    degree: "data-science",
    level: "degree",
    formula: "T = 0.1 * GAA + 0.3 * F + 0.2 * OPPE1 + 0.4 * OPPE2",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "OPPE1", label: "OPPE 1", description: "Online Programming Practice Exam 1", max: 100 },
      { id: "OPPE2", label: "OPPE 2", description: "Online Programming Practice Exam 2", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "dlcv",
    name: "Deep Learning for CV",
    degree: "data-science",
    level: "degree",
    formula: "T = 0.1 * GAA + 0.5 * F + max(0.2 * Qz1 + 0.2 * Qz2, 0.3 * max(Qz1, Qz2))",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "dv",
    name: "Data Visualization",
    degree: "data-science",
    level: "degree",
    formula: "T = 0.3 * GA + max(0.2 * Qz1 + 0.2 * Qz2, 0.3 * max(Qz1, Qz2)) + 0.3 * P + Bonus",
    formFields: [
      { id: "GA", label: "GA", description: "Graded Assignments", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "P", label: "Project", description: "Project Score", max: 100 },
    ],
  },
  {
    id: "me",
    name: "Managerial Economics",
    degree: "data-science",
    level: "degree",
    formula: "T = 0.15 * GAA + max(0.2 * Qz1 + 0.2 * Qz2 + 0.45 * F, 0.5 * F + 0.25 * max(Qz1, Qz2))",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "atb",
    name: "Algorithmic Thinking in Bioinformatics",
    degree: "data-science",
    level: "degree",
    formula: "T = 0.2 * GAA + max(0.2 * Qz1 + 0.2 * Qz2 + 0.4 * F, 0.45 * F + 0.25 * max(Qz1, Qz2))",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "i4",
    name: "Industry 4.0",
    degree: "data-science",
    level: "degree",
    formula: "T = A + 0.3 * F + 0.15 * (Qz1 + Qz2) + 0.05 * Game + 0.1 * Project",
    formFields: [
      { id: "A", label: "Assignments", description: "Best 2 out of 3 Assignments", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
      { id: "Game", label: "Game", description: "Game Score", max: 100 },
      { id: "Project", label: "Project", description: "Project Score", max: 100 },
    ],
  },
  {
    id: "mt",
    name: "Mathematical Thinking",
    degree: "data-science",
    level: "degree",
    formula: "T = 0.1 * GAA + max(0.6 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.2 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "lsm",
    name: "Linear Statistical Models",
    degree: "data-science",
    level: "degree",
    formula: "T = 0.1 * GAA + 0.5 * F + max(0.2 * Qz1 + 0.2 * Qz2, 0.3 * max(Qz1, Qz2))",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "cprog",
    name: "Programming in C",
    degree: "data-science",
    level: "degree",
    formula: "T = 0.05 * GAA + 0.1 * GAAP + 0.15 * Qz1 + 0.20 * OPPE1 + 0.20 * OPPE2 + 0.30 * F",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "GAAP", label: "GAAP", description: "Graded Assignment Autograded Programming", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "OPPE1", label: "OPPE 1", description: "Online Programming Practice Exam 1", max: 100 },
      { id: "OPPE2", label: "OPPE 2", description: "Online Programming Practice Exam 2", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "ff",
    name: "Financial Forensics",
    degree: "data-science",
    level: "degree",
    formula: "T = 0.1 * GAA + max(0.25 * Qz1 + 0.30 * GP1 + 0.35 * F, 0.5 * F + 0.3 * max(Qz1, GP1))",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "GP1", label: "Group Project 1", description: "First Group Project Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "nlp",
    name: "Introduction to Natural Language Processing",
    degree: "data-science",
    level: "degree",
    formula: "T = 0.1 * GAA + 0.5 * F + 0.2 * Qz1 + 0.2 * Qz2",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "cf",
    name: "Corporate Finance",
    degree: "data-science",
    level: "degree",
    formula: "T = 0.1 * GAA + 0.4 * F + 0.2 * Qz1 + 0.3 * Qz2",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "dlp",
    name: "Deep Learning Practice",
    degree: "data-science",
    level: "degree",
    formula:
      "T = 0.2 * GA + 0.15 * Quiz1 + 0.15 * Quiz2 + 0.15 * Quiz3 + 0.2 * BestNPPE + 0.15 * SecondBestNPPE + 0.1 * LowestNPPE",
    formFields: [
      { id: "GA", label: "GA", description: "Graded Assignment", max: 100 },
      { id: "Quiz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Quiz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "Quiz3", label: "Quiz 3", description: "Third Quiz Score", max: 100 },
      { id: "BestNPPE", label: "Best NPPE", description: "Best NPPE Score", max: 100 },
      { id: "SecondBestNPPE", label: "Second Best NPPE", description: "Second Best NPPE Score", max: 100 },
      { id: "LowestNPPE", label: "Lowest NPPE", description: "Lowest NPPE Score", max: 100 },
    ],
  },
  {
    id: "os",
    name: "Operating Systems",
    degree: "data-science",
    level: "degree",
    formula: "T = 0.1 * GAA + 0.4 * F + 0.25 * Qz1 + 0.25 * Qz2",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "stml",
    name: "Special Topics in ML (Reinforcement Learning)",
    degree: "data-science",
    level: "degree",
    formula: "T = 0.1 * GAA + 0.2 * GPA + max(0.2 * Qz1 + 0.2 * Qz2, 0.3 * max(Qz1, Qz2)) + 0.3 * F",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "GPA", label: "GPA", description: "Graded Project Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "bdbn",
    name: "Big Data & Biological Networks",
    degree: "data-science",
    level: "degree",
    formula: "T = 0.15 * GAA + max(0.2 * Qz1 + 0.2 * Qz2 + 0.45 * F, 0.5 * F + 0.25 * max(Qz1, Qz2))",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },

  // Add these Electronic System courses after the existing Data Science courses

  // Foundation Level - Electronic Systems
  {
    id: "eng1-es",
    name: "English - I",
    degree: "electronic-systems",
    level: "foundation",
    formula: "T = 0.1 * GAA + max(0.6 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.2 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "math-elec1",
    name: "Math for Electronics - I",
    degree: "electronic-systems",
    level: "foundation",
    formula: "T = 0.1 * GAA + max(0.6 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.2 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "estc",
    name: "Electronic Systems Thinking and Circuits",
    degree: "electronic-systems",
    level: "foundation",
    formula: "T = 0.1 * GAA + max(0.6 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.2 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "estc-lab",
    name: "Electronic Systems Thinking and Circuits Lab",
    degree: "electronic-systems",
    level: "foundation",
    formula: "T = 1 * (Attendance) * (0.5 * experiment + 0.5 * Report)",
    formFields: [
      { id: "Attendance", label: "Attendance", description: "Attendance Score", max: 100 },
      { id: "experiment", label: "Experiment", description: "Experiment Score", max: 100 },
      { id: "Report", label: "Report", description: "Report Score", max: 100 },
    ],
  },
  {
    id: "c-prog",
    name: "Introduction to C Programming",
    degree: "electronic-systems",
    level: "foundation",
    formula: "T = 0.1 * GAA + 0.2 * Qz1 + 0.4 * F + max(0.15 * OPPE1 + 0.15 * OPPE2, 0.20 * max(OPPE1, OPPE2))",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
      { id: "OPPE1", label: "OPPE 1", description: "Online Programming Practice Exam 1", max: 100 },
      { id: "OPPE2", label: "OPPE 2", description: "Online Programming Practice Exam 2", max: 100 },
    ],
  },
  {
    id: "c-prog-lab",
    name: "Introduction to C Programming Lab",
    degree: "electronic-systems",
    level: "foundation",
    formula: "T = 0.5 * (TLA) + 0.5 * (IL)",
    formFields: [
      { id: "TLA", label: "TLA", description: "Teacher Led Activities", max: 100 },
      { id: "IL", label: "IL", description: "Independent Learning", max: 100 },
    ],
  },
  {
    id: "eng2-es",
    name: "English - II",
    degree: "electronic-systems",
    level: "foundation",
    formula: "T = 0.1 * GAA + max(0.6 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.2 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "linux-prog",
    name: "Introduction to Linux and Programming",
    degree: "electronic-systems",
    level: "foundation",
    formula: "T = 0.1 * GAA + 0.05 * NPPE + 0.2 * Qz1 + 0.25 * OPPE + 0.3 * F + 0.05 * BPTA + 0.05 * VMT",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "NPPE", label: "NPPE", description: "Non-Programming Practice Exam", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "Quiz Score", max: 100 },
      { id: "OPPE", label: "OPPE", description: "Online Programming Practice Exam", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
      { id: "BPTA", label: "BPTA", description: "Best Practice Test Attempt", max: 100 },
      { id: "VMT", label: "VMT", description: "Virtual Machine Test", max: 100 },
    ],
  },
  {
    id: "linux-shell-lab",
    name: "Introduction to the Linux Shell Lab",
    degree: "electronic-systems",
    level: "foundation",
    formula: "T = 0.5 * (OL) + 0.5 * (IL)",
    formFields: [
      { id: "OL", label: "OL", description: "Online Learning", max: 100 },
      { id: "IL", label: "IL", description: "Independent Learning", max: 100 },
    ],
  },
  {
    id: "digital-systems",
    name: "Digital Systems",
    degree: "electronic-systems",
    level: "foundation",
    formula: "T = 0.1 * GAA + max(0.6 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.2 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "elec-circuits",
    name: "Electrical and Electronic Circuits",
    degree: "electronic-systems",
    level: "foundation",
    formula: "T = 0.1 * GAA + max(0.6 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.2 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "electronics-lab",
    name: "Electronics Lab",
    degree: "electronic-systems",
    level: "foundation",
    formula: "T = 0.4 * (WE) + 0.6 * (ID)",
    formFields: [
      { id: "WE", label: "WE", description: "Weekly Experiments", max: 100 },
      { id: "ID", label: "ID", description: "Independent Design", max: 100 },
    ],
  },
  {
    id: "embedded-c",
    name: "Embedded C Programming",
    degree: "electronic-systems",
    level: "foundation",
    formula: "T = 0.1 * GAA + 0.1 * GRPA + max((0.5 * F + 0.2 * max(Qz1, Qz2)), (0.4 * F + 0.2 * Qz1 + 0.2 * Qz2))",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "GRPA", label: "GRPA", description: "Group Assignment", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "embedded-c-lab",
    name: "Embedded C Programming Lab",
    degree: "electronic-systems",
    level: "foundation",
    formula: "T = 0.2 * (Attendance) + 0.8 * (LabExperiment)",
    formFields: [
      { id: "Attendance", label: "Attendance", description: "Attendance Score", max: 100 },
      { id: "LabExperiment", label: "Lab Experiment", description: "Lab Experiment and Viva Score", max: 100 },
    ],
  },

  // Diploma Level - Electronic Systems
  {
    id: "math-elec2",
    name: "Math for Electronics - II",
    degree: "electronic-systems",
    level: "diploma",
    formula: "T = 0.1 * GAA + max(0.6 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.2 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "signals-systems",
    name: "Signals and Systems",
    degree: "electronic-systems",
    level: "diploma",
    formula: "T = 0.1 * GAA + max(0.5 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.2 * Qz1 + 0.2 * Qz2) + 0.1 * GrPA",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
      { id: "GrPA", label: "GrPA", description: "Group Project Assignment", max: 100 },
    ],
  },
  {
    id: "python-es",
    name: "Python Programming",
    degree: "electronic-systems",
    level: "diploma",
    formula: "T = 0.1 * GAA1 + 0.1 * GAA2 + 0.1 * Qz1 + 0.4 * F + 0.25 * max(PE1, PE2) + 0.15 * min(PE1, PE2)",
    formFields: [
      { id: "GAA1", label: "GAA 1", description: "Graded Assignment Average 1", max: 100 },
      { id: "GAA2", label: "GAA 2", description: "Graded Assignment Average 2", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
      { id: "PE1", label: "PE 1", description: "Programming Exam 1", max: 100 },
      { id: "PE2", label: "PE 2", description: "Programming Exam 2", max: 100 },
    ],
  },
  {
    id: "analog-systems",
    name: "Analog Electronic Systems",
    degree: "electronic-systems",
    level: "diploma",
    formula: "T = 0.1 * GAA + max(0.6 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.2 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "analog-lab",
    name: "Analog Electronics Lab",
    degree: "electronic-systems",
    level: "diploma",
    formula: "T = 0.4 * (WE) + 0.6 * (ID)",
    formFields: [
      { id: "WE", label: "WE", description: "Weekly Experiments", max: 100 },
      { id: "ID", label: "ID", description: "Independent Design", max: 100 },
    ],
  },
  {
    id: "dsp",
    name: "Digital Signal Processing",
    degree: "electronic-systems",
    level: "diploma",
    formula:
      "T = 0.1 * GAA + 0.1 * LE + 0.05 * LV + max(0.55 * F + 0.1 * max(Qz1, Qz2), 0.45 * F + 0.15 * Qz1 + 0.15 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "LE", label: "LE", description: "Lab Experiments", max: 100 },
      { id: "LV", label: "LV", description: "Lab Viva", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "sensors",
    name: "Sensors and Application",
    degree: "electronic-systems",
    level: "diploma",
    formula: "T = 0.1 * GAA + max(0.6 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.2 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "sensors-lab",
    name: "Sensors Laboratory",
    degree: "electronic-systems",
    level: "diploma",
    formula: "T = 1 * (Attendance) * (0.5 * experiment + 0.5 * Report)",
    formFields: [
      { id: "Attendance", label: "Attendance", description: "Attendance Score", max: 100 },
      { id: "experiment", label: "Experiment", description: "Experiment Score", max: 100 },
      { id: "Report", label: "Report", description: "Report Score", max: 100 },
    ],
  },
  {
    id: "digital-system-design",
    name: "Digital System Design",
    degree: "electronic-systems",
    level: "diploma",
    formula: "T = 0.1 * GAA + 0.1 * GRPA + max((0.5 * F + 0.2 * max(Qz1, Qz2)), (0.4 * F + 0.2 * Qz1 + 0.2 * Qz2))",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "GRPA", label: "GRPA", description: "Group Assignment", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "digital-system-lab",
    name: "Digital System Design Laboratory",
    degree: "electronic-systems",
    level: "diploma",
    formula: "T = 0.2 * (Attendance) + 0.8 * (LabExperiment)",
    formFields: [
      { id: "Attendance", label: "Attendance", description: "Attendance Score", max: 100 },
      { id: "LabExperiment", label: "Lab Experiment", description: "Lab Experiment and Viva Score", max: 100 },
    ],
  },
  {
    id: "control-eng",
    name: "Control Engineering",
    degree: "electronic-systems",
    level: "diploma",
    formula: "T = 0.1 * GAA + 0.5 * F + 0.2 * Qz1 + 0.2 * Qz2",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
]
